export interface ApiError {
  title: string;
  status: number;
  detail: string;
  code: ErrorCode;
  timestamp: string;
}

export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  USERNAME_EMPTY = 'USERNAME_EMPTY',
  EMAIL_EMPTY = 'EMAIL_EMPTY',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  EXPIRED_REFRESH_TOKEN = 'EXPIRED_REFRESH_TOKEN',

  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',

  QUOTE_NOT_FOUND = 'QUOTE_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}